[package]
name = "cargo-tags"
version = "0.1.0"
authors = [
  "Andrew Radev <andrey.radev@gmail.com>",
  "Carol (Nichols || Goulding) <carol.nichols@gmail.com>"
]
readme = "README.md"
repository = "https://github.com/AndrewRadev/cargo-tags"
homepage = "https://github.com/AndrewRadev/cargo-tags"
license = "MIT/Apache-2.0"
description = "A third-party cargo extension that generates a ctags tag file for your packages"

[[bin]]
name = "cargo-tags"

[dependencies]
clap = "*"
cargo = "*"
