[package]
name = "cargo-src"
version = "0.1.0"
authors = ["Andrew Radev <andrey.radev@gmail.com>"]
readme = "README.md"
repository = "https://github.com/AndrewRadev/cargo-src"
homepage = "https://github.com/AndrewRadev/cargo-src"
license = "MIT/Apache-2.0"
description = "A third-party cargo extension that lists local source locations of dependencies"

[[bin]]
name = "cargo-src"

[dependencies]
clap = "*"
cargo = "0.32.0"
dirs = "1.0.5"
